# Generated by Django 2.2.4 on 2019-11-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsi.Professor'),
        ),
    ]
