# Generated by Django 2.2.7 on 2019-12-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsi', '0002_auto_20191127_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('profCoordenador', models.ForeignKey(on_delete=models.SET('0'), to='bsi.Professor')),
            ],
        ),
    ]
