# Generated by Django 2.2.7 on 2019-12-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsi', '0003_estagio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='vagaEstagio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsi.Estagio'),
        ),
    ]
